version: "3.9"

services:
  server:
    build: .
    container_name: server_netflixpp
    restart: always
    environment:
      BACKEND_HOST: host.docker.internal
      BACKEND_PORT: 8080
    ports:
      - "80:80"
      - "8081:8081"
      - "9001:9001"
    volumes:
      - ./storage:/app/storage
    command: ["java", "-jar", "build/libs/server-netflixpp.jar"]
